name: android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gettext

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Clone Minetest from Codeberg
        run: |
          git clone --depth 1 https://codeberg.org/halon/Minetest.git minetest

      - name: Clone mcl_localplayer mod
        working-directory: minetest
        run: |
          git clone --depth 1 https://codeberg.org/halon/mcl_localplayer.git clientmods/mcl_localplayer
          echo "load_mod_mcl_localplayer = true" > clientmods/mods.conf

      - name: Apply patch
        working-directory: minetest
        run: |
          git apply ../android/clientmods_android.diff

      # Ensure the standard debug keystore exists for later Release signing
      - name: Ensure debug keystore exists
        run: |
          mkdir -p "$HOME/.android"
          if [ ! -f "$HOME/.android/debug.keystore" ]; then
            keytool -genkeypair -v \
              -keystore "$HOME/.android/debug.keystore" \
              -alias androiddebugkey \
              -storepass android \
              -keypass android \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi
          ls -l "$HOME/.android/debug.keystore"

      # Build Debug first (produces 4 APKs: arm64-v8a, armeabi-v7a, x86, x86_64)
      - name: Build Debug APKs (all ABIs)
        working-directory: minetest/android
        run: ./gradlew --no-daemon assembleDebug -x lint -x test

      # Point Release signing at the debug keystore
      # build.gradle reads ../local.properties relative to android/app
      - name: Configure Release signing with debug keystore
        working-directory: minetest/android
        run: |
          {
            echo "keystore=$HOME/.android/debug.keystore"
            echo "keystore.password=android"
            echo "key=androiddebugkey"
            echo "key.password=android"
          } > local.properties
          cat local.properties

      # Build Release (signed with the debug key). This will emit split APKs for all ABIs.
      - name: Build Release APKs (signed with debug key)
        working-directory: minetest/android
        run: ./gradlew --no-daemon assembleRelease -x lint -x test

      - name: List built APKs
        run: |
          echo "Debug:"
          ls -lah minetest/android/app/build/outputs/apk/debug || true
          echo "Release:"
          ls -lah minetest/android/app/build/outputs/apk/release || true

      - name: Upload Debug APKs (all ABIs)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: minetest/android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Upload Release APKs (signed with debug key)
        uses: actions/upload-artifact@v4
        with:
          name: release-apks-debug-key
          path: minetest/android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error