name: android-arm64

on:
  workflow_dispatch:

jobs:
  build-arm64-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gettext

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Clone Minetest from Codeberg
        run: |
          git clone --depth 1 https://codeberg.org/halon/Minetest.git minetest

      - name: Clone mcl_localplayer mod
        working-directory: minetest
        run: |
          git clone --depth 1 https://codeberg.org/halon/mcl_localplayer.git clientmods/mcl_localplayer
          echo "load_mod_mcl_localplayer = true" > clientmods/mods.conf

      - name: Apply patch
        working-directory: minetest
        run: |
          git apply ../clientmods_android.diff       

      - name: Build AAB with Gradle
        # We build an AAB as well for uploading to the the Play Store.
        working-directory: minetest
        run: cd android; ./gradlew bundlerelease

      - name: Build APKs with Gradle
        # "assemblerelease" is very fast after "bundlerelease".
        working-directory: minetest
        run: cd android; ./gradlew assembledebug

      - name: Save AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luanti-release.aab
          path: minetest/android/app/build/outputs/bundle/release/app-release.aab

      - name: Save arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Luanti-arm64-v8a.apk
          path: minetest/android/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
