name: Oldosfan Minetest/Luanti Build (macOS arm64)

on:
  workflow_dispatch:

jobs:
  macos-arm64:
    runs-on: macos-14
    steps:
      - name: Clone Minetest from Codeberg
        run: |
          git clone --depth 1 https://codeberg.org/halon/Minetest.git minetest

      - name: Clone mcl_localplayer mod
        working-directory: minetest
        run: |
          git clone --depth 1 https://codeberg.org/halon/mcl_localplayer.git clientmods/mcl_localplayer
          echo "load_mod_mcl_localplayer = true" > clientmods/mods.conf

      - name: Remove preinstalled cmake and untap pinned
        run: |
          brew list --formula | grep -q '^cmake$' && brew uninstall --ignore-dependencies cmake || true
          brew untap local/pinned || true

      - name: Install deps
        working-directory: minetest
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
          HOMEBREW_NO_ANALYTICS: "1"
        shell: bash
        run: |
          set -euo pipefail
          source ./util/ci/common.sh
          install_macos_deps
          brew uninstall jsoncpp || true

      - name: Build with CMake
        working-directory: minetest
        run: |
          cmake -S . -B build \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=14 \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_INSTALL_PREFIX="${PWD}/build/macos" \
            -DRUN_IN_PLACE=FALSE \
            -DENABLE_GETTEXT=TRUE \
            -DENABLE_SYSTEM_JSONCPP=OFF
          cmake --build build -j"$(sysctl -n hw.logicalcpu)"
          cmake --install build

      - name: Write CPack install script
        working-directory: minetest
        run: |
          cat > cpack_install_clientmods.cmake <<'EOF'
          # CPack runs this during the staged install.
          # CMAKE_INSTALL_PREFIX is the CPack staging root.
          set(APP "${CMAKE_INSTALL_PREFIX}/luanti.app/Contents/Resources")
          file(MAKE_DIRECTORY "${APP}/clientmods")
          file(COPY "${CLIENTMOD_SRC}/mcl_localplayer" DESTINATION "${APP}/clientmods")
          file(COPY "${CLIENTMOD_SRC}/mods.conf"       DESTINATION "${APP}/clientmods")
          EOF

      - name: CPack
        working-directory: minetest
        run: |
          cd build
          rm -rf macos
          cmake .. -DINSTALL_DEVTEST=FALSE
          cpack -G ZIP -B macos \
            -D CPACK_INSTALL_SCRIPT="${PWD}/../cpack_install_clientmods.cmake" \
            -D CLIENTMOD_SRC="${PWD}/../clientmods"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luanti-macos
          path: minetest/build/macos/*.zip
          if-no-files-found: error
