name: Luanti macOS (arm64 from Codeberg, bundle clientmods)

on:
  workflow_dispatch:

jobs:
  build-arm-macos:
    runs-on: macos-14
    env:
      # Customize these to point at your forks/mods
      LUANTI_REPO_URL: https://codeberg.org/halon/Minetest.git
      LUANTI_DIR: luanti
      CLIENTMOD_REPO_URL: https://codeberg.org/halon/mcl_localplayer.git
      CLIENTMOD_DIR: clientmods/mcl_localplayer

      # Keep Homebrew quiet/fast and avoid dependency rechecks
      HOMEBREW_NO_AUTO_UPDATE: "1"
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: "1"
      HOMEBREW_NO_INSTALL_CLEANUP: "1"

    steps:
      - name: Prepare workspace
        uses: actions/checkout@v4

      - name: Clone Luanti from Codeberg
        run: |
          set -euo pipefail
          git clone --depth 1 "$LUANTI_REPO_URL" "$LUANTI_DIR"
          cd "$LUANTI_DIR"
          git submodule update --init --recursive || true

      - name: Clone clientmod(s) into Luanti tree
        working-directory: ${{ env.LUANTI_DIR }}
        run: |
          set -euo pipefail
          git clone --depth 1 "$CLIENTMOD_REPO_URL" "$CLIENTMOD_DIR"
          mkdir -p clientmods
          # Enable the mod by default (adjust the name to your mod dir)
          echo "load_mod_mcl_localplayer = true" > clientmods/mods.conf

      # Workaround for GitHub macOS runner having a pinned/local cmake that conflicts
      - name: Work around pinned Homebrew cmake
        run: |
          set -euo pipefail
          # If cmake exists (often from a local/pinned tap), remove it so core cmake can be installed by the deps script
          if brew list --formula cmake >/dev/null 2>&1; then
            brew unpin cmake || true
            brew uninstall --ignore-dependencies --force cmake || true
          fi
          # Ensure core tap is present
          brew tap homebrew/core || true

      - name: Install build dependencies
        working-directory: ${{ env.LUANTI_DIR }}
        run: |
          set -euo pipefail
          source ./util/ci/common.sh
          install_macos_deps
          # Homebrew jsoncpp causes header/lib conflicts with bundled one
          brew list jsoncpp >/dev/null 2>&1 && brew uninstall jsoncpp || true

      - name: Reinstall for packaging (strip devtest)
        working-directory: ${{ env.LUANTI_DIR }}
        run: |
          set -euo pipefail
          mkdir -p build
          cd build
          rm -rf ../build/macos
          cmake .. \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=14 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_INSTALL_PREFIX=../build/macos/ \
            -DRUN_IN_PLACE=FALSE \
            -DENABLE_GETTEXT=TRUE \
            -DENABLE_SYSTEM_JSONCPP=OFF \
            -DINSTALL_DEVTEST=FALSE
          cmake --build . -j"$(sysctl -n hw.logicalcpu)"
          make install

      - name: Inject clientmods into luanti.app/Contents/Resources
        working-directory: ${{ env.LUANTI_DIR }}
        run: |
          set -euo pipefail
          APP="build/macos/luanti.app"
          RES="$APP/Contents/Resources"
          SRC="clientmods"
          if [ -d "$SRC" ]; then
            mkdir -p "$RES/clientmods"
            rsync -a --delete --exclude '.git*' "$SRC/" "$RES/clientmods/"
            # Ensure mods.conf exists inside the bundle
            if [ ! -f "$RES/clientmods/mods.conf" ]; then
              if [ -f "$SRC/mods.conf" ]; then
                cp "$SRC/mods.conf" "$RES/clientmods/mods.conf"
              else
                printf "# enable mods here\n# load_mod_example = true\n" > "$RES/clientmods/mods.conf"
              fi
            fi
          else
            echo "No ./clientmods directory found; skipping injection."
          fi

      - name: Package .app (no CPack)
        working-directory: ${{ env.LUANTI_DIR }}
        run: |
          set -euo pipefail
          OUT="../luanti-macos-arm64.zip"
          rm -f "$OUT"
          # ditto preserves permissions and resource forks for macOS bundles
          ditto -c -k --sequesterRsrc --keepParent "build/macos/luanti.app" "$OUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luanti-macos-arm64
          path: luanti-macos-arm64.zip
          if-no-files-found: error
